# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=36)),
                ('short_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dateStart', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromMatch', to='betfight.event')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=150)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromTeam', to='betfight.event')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='teamGuest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='betfight.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamHome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='betfight.team'),
        ),
    ]
