# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='groupLetter',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
