# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfight', '0002_team_groupletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='koeffDraw',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='koeffGuest',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='koeffHome',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='totalTeamGuestScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='totalTeamHomeScore',
            field=models.IntegerField(null=True),
        ),
    ]
