# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfight', '0003_auto_20180417_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='totalTeamGuestScore',
            new_name='totalGuestScore',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='totalTeamHomeScore',
            new_name='totalHomeScore',
        ),
        migrations.AddField(
            model_name='match',
            name='baseGuestScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='baseHomeScore',
            field=models.IntegerField(null=True),
        ),
    ]
