# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfight', '0004_auto_20180420_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='isOver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='baseGuestScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='baseHomeScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='koeffDraw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='koeffGuest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='koeffHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='totalGuestScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='totalHomeScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
